# Generated by Django 3.2.25 on 2024-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20240821_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MSG', 'Message'), ('TRN', 'Tournament'), ('FRQ', 'Friend Request')], default='MSG', max_length=3),
        ),
    ]
