version: "3"
services:
  front-end:
    container_name: front-end
    build: "./front-end"
    ports:
      - "443:443"
    networks:
      - local
    restart: on-failure
    depends_on:
      - back-end
  back-end:
    container_name: back-end
    build: "./back-end"
    restart: on-failure
    volumes:
      - ./back-end:/back-end
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - local
    env_file:
      - ./back-end/.env
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - ./back-end/.env
    ports:
      - "5432:5432"
    networks:
      - local
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./back-end/.env
    ports:
      - "5050:80"
    networks:
      - local

networks:
  local:
    driver: bridge
