version: "3.8"
services:
  back-end:
    container_name: back-end
    build: "./back-end"
    volumes:
      - ./back-end:/back-end
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - local
  front-end:
    container_name: front-end
    image: nginx:latest
    volumes:
      - ./conf/nginx_spa.conf:/etc/nginx/nginx.conf
      - ./front-end:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - local
    restart: always
    depends_on:
      - back-end
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - local
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - local

networks:
  local:
    driver: bridge