# Generated by Django 3.2.25 on 2024-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matche_played', models.IntegerField(default=0)),
                ('matche_won', models.IntegerField(default=0)),
                ('matche_lost', models.IntegerField(default=0)),
                ('matche_draw', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('goals_difference', models.IntegerField(default=0)),
            ],
        ),
    ]
