# Generated by Django 3.2.25 on 2024-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='users_pfp/'),
        ),
    ]
