# Generated by Django 3.2.25 on 2024-08-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_stats_user'),
        ('user', '0005_alter_user_profile_pic_url'),
    ]

    operations = [
    ]
