# Generated by Django 3.2.25 on 2024-08-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paddle_type',
            field=models.CharField(default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='table_theme',
            field=models.CharField(default='mod', max_length=30),
        ),
    ]
