# Generated by Django 3.2.25 on 2024-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='FriendList',
            name='user1_invited_user2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='FriendList',
            name='user2_invited_user1',
            field=models.BooleanField(default=False),
        ),
    ]
