# Generated by Django 4.2.8 on 2024-09-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
