# Generated by Django 3.2.25 on 2024-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournamentparticipant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='chanel_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
