# Generated by Django 3.2.25 on 2024-08-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_rename_channel_name_tournamentparticipant_websocket_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='websocket_channel_name',
        ),
    ]
