# Generated by Django 3.2.25 on 2024-08-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_remove_tournamentparticipant_websocket_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='channel_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
