# Generated by Django 3.2.25 on 2024-08-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournamentparticipant_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipant',
            old_name='channel_name',
            new_name='websocket_channel_name',
        ),
    ]
