# Generated by Django 3.2.25 on 2024-08-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_rename_channel_name_tournamentparticipant_websocket_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipant',
            old_name='websocket_channel_name',
            new_name='room_group_name',
        ),
    ]
