# Generated by Django 3.2.25 on 2024-08-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_rename_websocket_channel_name_tournamentparticipant_room_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='room_group_name',
        ),
    ]
