# Generated by Django 3.2.25 on 2024-08-23 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0010_remove_tournamentparticipant_room_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='id',
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='player',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
