# Generated by Django 3.2.25 on 2024-08-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0011_auto_20240823_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
