# Generated by Django 3.2.25 on 2024-08-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_auto_20240823_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
