FROM python:3.7

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . back-end

WORKDIR /back-end

RUN chmod +x start.sh

EXPOSE 8000

CMD ["sh", "start.sh"]
