# Generated by Django 3.2.25 on 2024-06-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('profile_pic', models.ImageField(default=None, upload_to='users_pfp/')),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
