# Generated by Django 3.2.25 on 2024-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_auth', '0003_auto_20240611_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='users_pfp/'),
        ),
    ]
