# Generated by Django 3.2.25 on 2024-06-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_auth', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
