# Generated by Django 3.2.25 on 2024-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_auth', '0004_auto_20240614_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stats',
        ),
    ]
