# Generated by Django 3.2.25 on 2024-06-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_auth', '0005_auto_20240625_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
